# ---------------------------------------------------------------------------- #
[ConsoleLog]
# ---------------------------------------------------------------------------- #

# Флаг отвечает за вывод имени файла исходного, номера строки и имени функции
# в исходном коде.
needSourceLocation = false

# Флаг отвечает за вывод идентификатора потока в лог.
needThreadId = true

# Параметр отвечает за формат вывода даты и времени.
dateTimeFormat = %Y-%m-%d %H:%M:%S.%f

# Минимальный уровень важности фиксируемых сообщений.
severityLevel = info



# ---------------------------------------------------------------------------- #
[FileLog]
# ---------------------------------------------------------------------------- #

# Путь к папке с логами.
logPath = ./logs/

# Параметр отвечает за создание нового файла лога, когда текущий достигает
# заданного размера. Значение по умолчанию 10 МБ.
rotationSize = 10485100

# Флаг отвечает за вывод имени файла исходного, номера строки и имени функции
# в исходном коде.
needSourceLocation = true

# Флаг отвечает за вывод идентификатора потока в лог файл.
needThreadId = true

# Параметр отвечает за формат вывода даты и времени.
dateTimeFormat = %Y-%m-%d %H:%M:%S.%f

# Минимальный уровень важности фиксируемых сообщений.
severityLevel = info



# ---------------------------------------------------------------------------- #
[Database]
# ---------------------------------------------------------------------------- #

# Имя файла базы данных.
file = database.sqlite



# ---------------------------------------------------------------------------- #
[Network]
# ---------------------------------------------------------------------------- #

# Имя подключения к службе предоставления данных.
apiHost = 0.0.0.0

# Порт подключения к службе предоставления данных.
apiPort = 8090
